INSERT INTO cuisine_type (id, name) values (1, 'Chinese');
INSERT INTO cuisine_type (id, name) values (2, 'Japanese');
INSERT INTO cuisine_type (id, name) values (3, 'Bakery');
INSERT INTO cuisine_type (id, name) values (4, 'Coffee');
INSERT INTO cuisine_type (id, name) values (5, 'Desserts');
INSERT INTO cuisine_type (id, name) values (6, 'Brazilian');
INSERT INTO cuisine_type (id, name) values (7, 'Hamburgers');
INSERT INTO cuisine_type (id, name) values (8, 'Healthy Food');
INSERT INTO cuisine_type (id, name) values (9, 'Ice Creams');
INSERT INTO cuisine_type (id, name) values (10, 'Pizza');